language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq

install:
  - pip install pep8
  - pip install --upgrade pyflakes

before_script:
 - pep8 *.py --ignore=E501
  # to have the list anyway
 - pep8 *.py --select=E501 || true

script:
 - python3 euler.py
 - python3 prime.py
 - python3 functions.py
