language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "3.5.0b2"
  - "3.5.0b3"
#  - "nightly"
  - "pypy"
  - "pypy3"

before_install:
  - sudo apt-get update -qq

install:
  - pip install pep8
  - pip install --upgrade pyflakes

before_script:
 - pep8 *.py --ignore=E501
  # to have the list anyway
 - pep8 *.py --select=E501 || true
 - ./get_resources.sh

script:
 - python euler.py
 - python prime.py
 - python functions.py
